// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>> load(String fullPath, Locale locale ) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> ar = {
   "appBar1": "أكتشف",
   "appBar2": "الرسائل",
   "appBar3": "حسابي",
   "teacherAppBar1": "خدماتي",
   "teacherAppBar2": "اضافه خدمه",
   "teacherAppBar3": "الرسائل",
   "teacherAppBar4": "حسابي",
    "teacherPending": "الحساب ما زال معلق",
   "welcome": "صباح الخير,",
    "email": "البريد الالكتروني",
    "password": "كلمه المرور",
    "login": "تسجيل الدخول",
    "doNotHave": "ليس لديك حساب",
    "register": "انشاء حساب",
    "joinAs": "انضم كمدرس",
    "backAs": "العوده كطالب",
    "getHelp": "المساعده",
    "Name": "الاسم",
    "phoneNumber": "رقم الهاتف",
    "chooseField": "اختر مجالك",
    "chooseGender": "اختر الجنس",
    "applyHead": "قدم ملفك",
    "apply": "تقديم!",
    "registerSubHead": "سجل الدخول الان واكتشف اجدد المدرسين, ",
   "infoBar": "متعلم اليوم هو  ",
   "services": "خدماتنا ",
   "availableSubjects": "المواد المتاحه للدراسه: ",
   "info": "لنفسي",
   "service1": "مدرس",
   "service2": "كورسات",
   "subject1": "فيزياء",
   "subject2": "الكيمياء",
   "noMessages1": "لا توجد رسائل",
   "noMessages2": "ابحث عن محادثاتك هنا",
   "settingsInfo1": "عرض الملف الشخصي",
   "settingsInfo2": "الاشعرات",
   "settingsInfo3": "مساعده",
   "settingsInfo4": "تسجيل الخروج",
   "settingsInfo5": "اللغه",
   "Arabic": "العربيه",
   "Art": "الفن",
   "Biology": "الاحياء",
   "Chemistry": "الكيمياء",
   "English": "الانجليزيه",
   "French": "الفرنسيه",
   "General": "العامه",
   "Geology": "جيولوجيا",
   "German": "الماني",
   "History": "تاريخ",
   "Italian": "ايطالي",
   "Math": "رياضيات",
   "Philosophy": "فلسفه",
   "Physics": "فيزياء",
   "Programming": "برمجه",
   "Quran": "قرأن",
   "Religion": "ديانات",
   "Science": "علوم",
   "Spanish": "اسباني",
   "Social Studies": "دراسات اجتماعيه",
   "chooseSubject": "اختر ماده",
};
static const Map<String,dynamic> en = {
  "appBar1": "Explore",
  "appBar2": "Messages",
  "appBar3": "Settings",
  "teacherAppBar1": "Services",
  "teacherAppBar2": "Add Services",
  "teacherAppBar3": "Messages",
  "teacherAppBar4": "Settings",
  "teacherPending": "Your Account is still Pending",
  "welcome": "Good evening,",
  "email": "Email",
  "password": "Password",
  "login": "Login",
  "doNotHave": "Don't have an account",
  "register": "REGISTER",
  "joinAs": "Join as tutor",
  "backAs": "Back as Student",
  "getHelp": "Get Help",
  "Name": "Name",
  "phoneNumber": "Phone number",
  "chooseField": "Choose Field",
  "chooseGender": "Choose Gender",
  "applyHead": "Apply Your Profile",
  "apply": "Apply!",
  "registerSubHead": "Register now and discover our teachers, ",
  "infoBar": "Today's learner is ",
  "services": "Our Services",
  "availableSubjects": "Your available subjects for studying:",
  "info": "Me",
  "service1": "Tutors",
  "service2": "Courses",
  "subject1": "Physics",
  "subject2": "Chemistry",
  "noMessages1": "No Current messages",
  "noMessages2": "Find all your ongoing chats here",
  "settingsInfo1": "View full profile",
  "settingsInfo2": "Notifications",
  "settingsInfo3": "Help",
  "settingsInfo4": "Logout",
  "settingsInfo5": "Language",
  "Arabic": "Arabic",
  "Art ": "Art",
  "Biology": "Biology",
  "Chemistry": "Chemistry",
  "English": "English",
  "French": "French",
  "General": "General",
  "Geology": "Geology",
  "German": "German",
  "History": "History",
  "Italian": "Italian",
  "Math": "Math",
  "Philosophy": "Philosophy",
  "Physics": "Physics",
  "Programming": "Programming",
  "Quran": "Quran",
  "Religion": "Religion",
  "Science": "Science",
  "Spanish": "Spanish",
  "Social Studies": "Social Studies",
  "chooseSubject": "choose Subject",
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": ar, "en": en};
}
